spring.application.name=franchises

# Database Configuration MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


#Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#Swagger / OpenAPI
springdoc.default-produces-media-type=application/json
